2023-02-14 03:37:26,133 INFO    MainThread:1569 [internal.py:wandb_internal():89] W&B internal server running at pid: 1569, started at: 2023-02-14 03:37:26.132574
2023-02-14 03:37:26,139 INFO    WriterThread:1569 [datastore.py:open_for_write():77] open: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_033724-2alvzfm1/run-2alvzfm1.wandb
2023-02-14 03:37:26,141 DEBUG   HandlerThread:1569 [handler.py:handle_request():126] handle_request: run_start
2023-02-14 03:37:30,692 DEBUG   HandlerThread:1569 [meta.py:__init__():40] meta init
2023-02-14 03:37:30,692 DEBUG   HandlerThread:1569 [meta.py:__init__():54] meta init done
2023-02-14 03:37:30,693 DEBUG   HandlerThread:1569 [meta.py:probe():211] probe
2023-02-14 03:37:30,701 DEBUG   HandlerThread:1569 [meta.py:_setup_git():201] setup git
2023-02-14 03:37:30,758 DEBUG   HandlerThread:1569 [meta.py:_setup_git():208] setup git done
2023-02-14 03:37:30,759 DEBUG   HandlerThread:1569 [meta.py:_save_pip():58] save pip
2023-02-14 03:37:30,761 DEBUG   HandlerThread:1569 [meta.py:_save_pip():72] save pip done
2023-02-14 03:37:30,762 DEBUG   HandlerThread:1569 [meta.py:_save_conda():79] save conda
2023-02-14 03:37:45,764 DEBUG   HandlerThread:1569 [meta.py:_save_conda():87] save conda done
2023-02-14 03:37:45,764 DEBUG   HandlerThread:1569 [meta.py:probe():249] probe done
2023-02-14 03:38:03,941 WARNING MainThread:1569 [internal.py:wandb_internal():145] Internal process interrupt: 1
2023-02-14 03:38:04,316 WARNING MainThread:1569 [internal.py:wandb_internal():145] Internal process interrupt: 2
2023-02-14 03:38:04,316 ERROR   MainThread:1569 [internal.py:wandb_internal():148] Internal process interrupted.
2023-02-14 03:38:05,019 INFO    WriterThread:1569 [datastore.py:close():281] close: /home/bhavyajeet.singh/msme/MEMS-XF2T/generation/mT5-baseline/wandb/offline-run-20230214_033724-2alvzfm1/run-2alvzfm1.wandb
2023-02-14 03:38:05,022 INFO    HandlerThread:1569 [handler.py:finish():683] shutting down handler
2023-02-14 03:38:05,160 INFO    SenderThread:1569 [sender.py:finish():986] shutting down sender
2023-02-14 03:38:05,163 INFO    MainThread:1569 [internal.py:handle_exit():76] Internal process exited
